### PR TITLE
Add multistage Dockerfile

### PR DESCRIPTION
**Pull request by Vanuan**
This would enable automatic builds on Docker Hub

### CODE REVIEW

**Comment by Vanuan** [comment]
@thebsdbox Is this a legitimate failure?

**Comment by thebsdbox** [comment]
@Vanuan Not sure if I'd recommend bumping the `FROM` to more recent golang-alpine given the vulnerability news last week.

**Comment by thebsdbox** [comment]
No worries, I’ll bump the golang base image in another PR.

**Comment by thebsdbox** [comment]
... I’ve lost my write privileges.

**Comment by thebsdbox** [comment]
Thanks @Vanuan 👍🏻

**Pull request merged**
