### PR TITLE
Add an example using the swarm flavor plugin

### LINKED ISSUE #204: ./example/flavor/swarm needs documenting
A README in the style of the tutorial would be very nice.

Extra points for tying it into the Terraform example, showing how to deploy a swarm onto some terraformed instances.

### PR DESCRIPTION
**Pull request by wfarner**
Additionally, this removes shell code to install Docker.  Since we now have the
ability to compose plugins (using the combo flavor plugin), this is best done with composition.

Closes #204

Signed-off-by: Bill Farner <bill@docker.com>

### CODE REVIEW

**Comment by linsun** [comment]
Thank you @wfarner!  I will try it tmr.   Qs:
- I don't quite understand why docker install step is removed (e.g. wget -qO- https://get.docker.com/ | sh) in the  flavor.go.  How would we install docker engine on the host?  Is it because the box file already has docker installed?
- I don't see "type": "manager" specified in the swarm-managers group.json.   I noticed the flavor-swarm isn't used here either.  is that designed?
- how are you proposing to get the IP before the swarm manager group is deployed?
- I think I'm missing how this works, could you explain why swarm node is getting the manager's Ip from swarm plugin's flavor.go?

**Comment by wfarner** [comment]
@linsun it's not exactly straightforward, so i'd be more worried if you didn't have questions :-)

> How would we install docker engine on the host? Is it because the box file already has docker installed?

That's the preference.  Alternatively, you can also install it with shell code using the `vanilla` flavor _before_ the `swarm` flavor, leveraging the flavor [`combo`](https://github.com/docker/infrakit/tree/master/example/flavor/combo) to compose the two

> I don't see "type": "manager" specified in the swarm-managers group.json. I noticed the flavor-swarm isn't used here either. is that designed?

This is a result of me trying to put together a very simple example with minimal code changes.  The Swarm flavor faces a 'bootstrapping' challenge, where exactly one node must run `swarm init`, and must do so _before_ any other manager or worker nodes are created.  InfraKit doesn't have any sort of sequencing like that right now, so i've pushed the initialization and sequencing to the user (create manager group, wait, create worker group).

> how are you proposing to get the IP before the swarm manager group is deployed?

In this case, the IP address is dictated in the `LogicalID` and must be accommodated by the instance plugin.  In the case of Swarm in particular, using stable IP addresses is beneficial as Swarm uses this to identify nodes in the raft cluster.  As a result, instances being updated or re-provisioned causes less raft churn and induces less overall risk in managing the raft state.

> I think I'm missing how this works, could you explain how swarm node is getting the manager's Ip from swarm plugin's flavor.go?

There's two relevant details:
- the swarm plugin is configured to use the manager's IP address for Docker API calls:
```shell
$ build/infrakit-flavor-swarm --host tcp://192.168.2.200:4243
```

- when asked to provision a node, we inject a boot script that uses `ManagerStatus.Addr` from the Docker API to construct the join command:

```
docker swarm join {{.MY_IP}} --token {{.JOIN_TOKEN}}
```

**Stepping back**

This is not the ideal InfraKit/Swarm integration we're picturing.  The ideal setup looks something more like:
- InfraKit runs _on_ the swarm manager nodes, and piggy-backs on swarm's leader election for mutual exclusion
- A bootstrap routine creates the first manager node, runs `swarm init`, and starts InfraKit
- Persistent volumes are used to detach raft state from the compute nodes

There's more work to be done to enable that setup, including #244 and likely some yet-to-be-created issues.

**Comment by linsun** [comment]
@wfarner thanks for answering my questions in detail, much appreciated!  I'm working with VM from IBM Bluemix/Softlayer, where I cannot really assign an IP when I provision a VM today.  One workaround I can think of is to use the vanilla flavor and grab the public ip from user data script (I need to double check to see if the public ip is assigned when the script is executed), and use that to configure the swarm mgr.   If i do that, I'm having trouble to think how to pass the mgr IP to the node as the mgr IP is only configured in the mgr's group.json, not the node's group.json from your example.  In the flavor.go prepare method, you had:

	self, _, err := s.client.NodeInspectWithRaw(context.Background(), nodeInfo.Swarm.NodeID)

which seems to be able to get the nodeInfo that contains the ManagerStatus.Addr, however, how is the mgr's address obtained before the swarm node joins the mgr (which happens a few lines later when generateInitScript() is called)?  This was where I was quite confused....

The combo plugin is an interesting concept, thanks for sharing that!

I agree that if infrakit runs on the mgr node, it will be much easier to discover the mgr, find the join token, watch the node, etc.

**Comment by wfarner** [comment]
@linsun the case of provisioning managers with dynamic IPs is going to be tricky and require some careful thought.  Can i trouble you to file an issue so we can track and continue the discussion?

**Comment by linsun** [comment]
@wfarner good suggestion - opened https://github.com/docker/infrakit/issues/252 so we can continue discussion there!

**Comment by linsun** [comment]
Q @wfarner, if I stand up my swarm mgr (not known the ip till it is up running), and then when I launch the swarm flavor plugin and pass in the mgr ip, similar like ( build/infrakit-flavor-swarm --host tcp://{mgr_ip}:4243), I think I still shall be able to get the node joined the swarm cluster, no?  I plan to give this try with a combo plugin where it uses vanilla flavor to install docker, then use the swarm flavor to join the cluster.

**Comment by wfarner** [comment]
@linsun yup, that should work just fine!

**Comment by linsun** [comment]
@wfarner great, thanks for confirming that!

**Comment by wfarner** [comment]
@linsun another approach worth exploring is running InfraKit directly on the manager node.  This allows you to avoid specifying the IP address.  I'm hoping we will have a demonstration of this kind of behavior in the next week or two.

**Comment by linsun** [comment]
@wfarner Thanks!  I thought about that too... I 'd like to try that after I get the simple path discussed few hours ago working.  If we run infrakit directly on mgr node, perhaps we could develop a simple infrakit flavor to have infrakit installed?

**Comment by wfarner** [comment]
@linsun 

> If we run infrakit directly on mgr node, perhaps we could develop a simple infrakit flavor to have infrakit installed?

My plan was just to use shell code in the vanilla plugin to do this.  As intrigued as i am by the meta nature of an infrakit flavor plugin, i'm struggling to find a benefit over shell code :-)

**Comment by linsun** [comment]
@wfarner Ah, i see.  Shell code is great.   Having a flavor will allow code reuse, as you'll need to install go lang, infrakit including various plugins plus terraform assuming terraform is used for instances.

**Comment by linsun** [comment]
BTW, @wfarner I tried to stand up a swarm node by using build/infrakit-flavor-swarm --host tcp://{mgr_ip}:4243.   It took me quite a while to figure out where it failed, the swarm join cmd failed when I ran manually:   Error response from daemon: Timeout was reached before node was joined. The attempt to join the swarm will continue in the background. Use the "docker info" command to see the current swarm status of your node.

I then discovered port 2377 works fine if I replace the same docker swarm join cmd with port 2377 instead of 4243.  Going to try " build/infrakit-flavor-swarm --host tcp://{mgr_ip}:2377" to see if it works.

**Comment by linsun** [comment]
"build/infrakit-flavor-swarm --host tcp://{mgr_ip}:2377"  failed quickly with "ERRO[0098] Prepare phase failed to fetch Swarm join tokens error=Get http://{mgr_ip}:2377/v1.24/swarm: malformed HTTP response "\x15\x03\x01\x00\x02\x02"...

**Comment by linsun** [comment]
@wfarner -- I've gotten this working on my 2nd try... not sure why the first try didn't work, but I've added a bunch more info/debug statement to help out on 2nd try.  It could be that I didn't wait long enough for the first try as it takes time to get the docker installed plus join swarm cluster.   The ports were fine after all!  Going to try run infrakit on mgr node tmr.

**Comment by wfarner** [comment]
@linsun that's great to hear!  I've also made quite a bit of progress on my bootstrapping PR.  Still a work in progress, but you can see it over here: https://github.com/docker/infrakit.aws/pull/17

**Pull request merged**
