### PR TITLE
Update 'group describe-update' to 'group describe'

### PR DESCRIPTION
**Pull request by zsuzhengdu**
To align with terminal output
```
~/go/src/github.com/docker/infrakit (master) $ build/infrakit group -h
Access group plugin

Usage:
  build/infrakit group [command]

Available Commands:
  describe        describes the steps to perform an update
  describe-groups describe the groups
  destroy         destroy a group
  inspect         inspect a group
  stop            stop updating a group
  unwatch         unwatch a group
  update          update group (update < file or update filename)
  watch           watch a group

Flags:
      --name string   Name of plugin (default "group")

Global Flags:
      --log int   Logging level. 0 is least verbose. Max is 5 (default 4)

Use "build/infrakit group [command] --help" for more information about a command.
```

### CODE REVIEW

**Comment by wfarner** [comment]
I recently renamed some commands in #272, and i think the doc will appear correct if you run `make binaries` again.

**Comment by zsuzhengdu** [comment]
Did, but not sure why still getting ```describe```, but not ```describe-update```.

```
~/infrakit (master) $ git log
commit f3e4a288b4013bef8269cef71f90e4b4bdce867b
Author: Bill Farner <bill@docker.com>
Date:   Tue Nov 1 20:30:41 2016 -0700

    CLI: fix help text on group update (#273)

    Signed-off-by: Bill Farner <bill@docker.com>
```
Build again
```
~/infrakit (master) $ make binaries
+ clean
rm -rf build
mkdir -p build
+ build-binaries
go build -o build/infrakit -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/cmd/cli
go build -o build/infrakit-group-default -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/cmd/group
go build -o build/infrakit-flavor-combo -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/example/flavor/combo
go build -o build/infrakit-flavor-swarm -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/example/flavor/swarm
go build -o build/infrakit-flavor-vanilla -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/example/flavor/vanilla
go build -o build/infrakit-flavor-zookeeper -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/example/flavor/zookeeper
go build -o build/infrakit-instance-file -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/example/instance/file
go build -o build/infrakit-instance-terraform -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/example/instance/terraform
go build -o build/infrakit-instance-vagrant -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/example/instance/vagrant
```
```
~/infrakit (master) $ ./build/infrakit group -h
Access group plugin

Usage:
  ./build/infrakit group [command]

Available Commands:
  describe        describes the steps to perform an update
  describe-groups describe the groups
  destroy         destroy a group
  inspect         inspect a group
  stop            stop updating a group
  unwatch         unwatch a group
  update          update group (update < file or update filename)
  watch           watch a group

Flags:
      --name string   Name of plugin (default "group")

Global Flags:
      --log int   Logging level. 0 is least verbose. Max is 5 (default 4)
```

**Comment by wfarner** [comment]
Interesting!  I don't repro:
```shell
$ git log -1
commit f3e4a288b4013bef8269cef71f90e4b4bdce867b
Author: Bill Farner <bill@docker.com>
Date:   Tue Nov 1 20:30:41 2016 -0700

    CLI: fix help text on group update (#273)

    Signed-off-by: Bill Farner <bill@docker.com>
```

```shell
$ make binaries
+ clean
rm -rf build
mkdir -p build
+ build-binaries
go build -o build/infrakit -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/cmd/cli
go build -o build/infrakit-group-default -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/cmd/group
go build -o build/infrakit-flavor-combo -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/example/flavor/combo
go build -o build/infrakit-flavor-swarm -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/example/flavor/swarm
go build -o build/infrakit-flavor-vanilla -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/example/flavor/vanilla
go build -o build/infrakit-flavor-zookeeper -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/example/flavor/zookeeper
go build -o build/infrakit-instance-file -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/example/instance/file
go build -o build/infrakit-instance-terraform -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/example/instance/terraform
go build -o build/infrakit-instance-vagrant -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/example/instance/vagrant
```

```shell
$ build/infrakit group -h
Access group plugin

Usage:
  build/infrakit group [command]

Available Commands:
  describe-update describe the steps to perform an update
  destroy         destroy a group
  inspect         inspect a group
  ls              list groups
  stop-update     stop updating a group
  unwatch         unwatch a group
  update          update a group
  watch           watch a group

Flags:
      --name string   Name of plugin (default "group")

Global Flags:
      --log int   Logging level. 0 is least verbose. Max is 5 (default 4)

Use "build/infrakit group [command] --help" for more information about a command.
```

What's the output of `build/infrakit version` for you?

```shell
$ build/infrakit version
Version: f3e4a28
Revision: f3e4a288b4013bef8269cef71f90e4b4bdce867b
```

**Comment by zsuzhengdu** [comment]
Wired! Same version

```
~/infrakit (master) $ build/infrakit version
Version: f3e4a28
Revision: f3e4a288b4013bef8269cef71f90e4b4bdce867b
~/infrakit (master) $ build/infrakit group -h
Access group plugin

Usage:
  build/infrakit group [command]

Available Commands:
  describe        describes the steps to perform an update
  describe-groups describe the groups
  destroy         destroy a group
  inspect         inspect a group
  stop            stop updating a group
  unwatch         unwatch a group
  update          update group (update < file or update filename)
  watch           watch a group

Flags:
      --name string   Name of plugin (default "group")

Global Flags:
      --log int   Logging level. 0 is least verbose. Max is 5 (default 4)

Use "build/infrakit group [command] --help" for more information about a command.
~/infrakit (master) $
```

**Comment by zsuzhengdu** [comment]
Now it's working after ```git pull```

```
~/go/src/github.com/docker/infrakit (master) $ git pull
remote: Counting objects: 18, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 18 (delta 11), reused 18 (delta 11), pack-reused 0
Unpacking objects: 100% (18/18), done.
From https://github.com/docker/infrakit
   a263847..f3e4a28  master     -> origin/master
Updating a263847..f3e4a28
Fast-forward
 cmd/cli/group.go                          | 12 ++++++------
 docs/tutorial.md                          |  2 +-
 example/instance/terraform/cattle_demo.md |  2 +-
 scripts/tutorial_test                     |  2 +-
 4 files changed, 9 insertions(+), 9 deletions(-)
~/go/src/github.com/docker/infrakit (master) $
~/go/src/github.com/docker/infrakit (master) $
~/go/src/github.com/docker/infrakit (master) $ make binaries
+ clean
rm -rf build
mkdir -p build
+ build-binaries
go build -o build/infrakit -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/cmd/cli
go build -o build/infrakit-group-default -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/cmd/group
go build -o build/infrakit-flavor-combo -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/example/flavor/combo
go build -o build/infrakit-flavor-swarm -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/example/flavor/swarm
go build -o build/infrakit-flavor-vanilla -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/example/flavor/vanilla
go build -o build/infrakit-flavor-zookeeper -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/example/flavor/zookeeper
go build -o build/infrakit-instance-file -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/example/instance/file
go build -o build/infrakit-instance-terraform -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/example/instance/terraform
go build -o build/infrakit-instance-vagrant -ldflags "-X github.com/docker/infrakit/cli.Version=f3e4a28 -X github.com/docker/infrakit/cli.Revision=f3e4a288b4013bef8269cef71f90e4b4bdce867b" github.com/docker/infrakit/example/instance/vagrant
~/go/src/github.com/docker/infrakit (master) $ ls
CONTRIBUTING.md	Makefile	cattle.json	circle.yml	discovery	example		mock		scripts		tutorial
LICENSE		README.md	cattle2.json	cli		dockerfiles	garethr.json	plugin		spi		vendor
MAINTAINERS	build		cattle3.json	cmd		docs		images		rpc		templates	vendor.conf
~/go/src/github.com/docker/infrakit (master) $ ./build/infrakit version
Version: f3e4a28
Revision: f3e4a288b4013bef8269cef71f90e4b4bdce867b
~/go/src/github.com/docker/infrakit (master) $ ./build/infrakit group -h
Access group plugin

Usage:
  ./build/infrakit group [command]

Available Commands:
  describe-update describe the steps to perform an update
  destroy         destroy a group
  inspect         inspect a group
  ls              list groups
  stop-update     stop updating a group
  unwatch         unwatch a group
  update          update a group
  watch           watch a group

Flags:
      --name string   Name of plugin (default "group")

Global Flags:
      --log int   Logging level. 0 is least verbose. Max is 5 (default 4)

Use "./build/infrakit group [command] --help" for more information about a command.
~/go/src/github.com/docker/infrakit (master) $ git log
commit f3e4a288b4013bef8269cef71f90e4b4bdce867b
Author: Bill Farner <bill@docker.com>
Date:   Tue Nov 1 20:30:41 2016 -0700

    CLI: fix help text on group update (#273)

    Signed-off-by: Bill Farner <bill@docker.com>
```

**Comment by wfarner** [comment]
Phew, glad you're sorted out.  Thanks for the quick replies!

**Pull request closed without merging**
